name: IOS Develop Build

on: workflow_dispatch

jobs:
  ios-build:
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ios

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
        
      - name: Install npm dependencies
        run: |
          npm install
      
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
          
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: pod install --repo-update && pwd && cd ..
          
      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ios/flexinvest.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.IOS_CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ios/flexinvest.xcworkspace
          scheme: flexinvest

      - name: Save log file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log-file
          path: /Users/runner/Library/Logs/gym/flexinvest-flexinvest.log
