name: react-native-android-build-apk
on: workflow_dispatch
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install npm dependencies
        run: |
          npm install
      
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
        
      - name: GET NEW VERSION
        run: cd android && echo NEWNUM=`./gradlew -q printNewVersionName` >> $GITHUB_ENV
        
#       - name: Run build script
#         run: ./.github/scripts/build.sh
#         shell: bash
        
      - name: Display version
        run: echo ${{ env.NEWNUM }}
        
#       - name: Test
#         run: echo $(($GITHUB_ENV))
        
#       - name: Tag Release
#         run: |
#           version_name=${{ env.GITHUB_ENV }}
#           echo "Tagging release with tag" ${{ env.GITHUB_ENV }}
#           git tag ${{ env.GITHUB_ENV }}
#           git push origin --tags

#       - name: Run build script
#         run: |
#           sed -i "s/versionName \"1.111\"/versionName \"1.${{ env.GITHUB_ENV }}\"/" android/app/build.gradle --debug
#         shell: bash

#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
          
#       - name: Find and Replace
#         uses: jacobtomlinson/gha-find-replace@v2
#         with:
#           find: "1.231"
#           replace: "1.111"
#           regex: false
          
#       - name: Push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
          
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: android/app/build.gradle # or app/build.gradle.kts 
          versionCode: 555
          versionName: "4.444"
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated version
          
#       - name : Retrieve Version
#         run: |
#           cd android && ./gradlew -q printVersionName
#         id: android_version
        
#       - name : Retrieve Version
#         run: |
#          echo "::set-output name=VERSION_NAME::$(/gradlew -q printVersionName)"
        
#       - name: Get version
#         run: |
#           echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
          
#       - name: Get version
#         run: |
#           echo ${{env.version_name}}
        
#   build-android:
#     needs: install-and-test
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: actions/checkout@v2
#       - name: Install npm dependencies
#         run: |
#           npm install
#       - name: Build Android Release
#         run: |
#           cd android && ./gradlew assembleRelease
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-release.apk
#           path: android/app/build/outputs/apk/release/
