name: react-native-android-build-apk
on: workflow_dispatch
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install npm dependencies
        run: |
          npm install
      
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
        
      - name: Set BUILD VERSION
        run: cd android && ./gradlew -q printVersionName >> $GITHUB_ENV
        
      - name: Test
        run: echo $GITHUB_SHA_SHORT
          
#       - name : Retrieve Version
#         run: |
#           cd android && ./gradlew -q printVersionName
#         id: android_version
        
#       - name : Retrieve Version
#         run: |
#          echo "::set-output name=VERSION_NAME::$(/gradlew -q printVersionName)"
        
#       - name: Get version
#         run: |
#           echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
          
#       - name: Get version
#         run: |
#           echo ${{env.version_name}}
        
#   build-android:
#     needs: install-and-test
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: actions/checkout@v2
#       - name: Install npm dependencies
#         run: |
#           npm install
#       - name: Build Android Release
#         run: |
#           cd android && ./gradlew assembleRelease
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-release.apk
#           path: android/app/build/outputs/apk/release/
